In [2]:
import json
import pandas as pd
import numpy as np

import re

from sqlalchemy import create_engine
import psycopg2

# from config import db_password
from config import db_password
import time

# 1. Create a function that takes in three arguments;
# Wikipedia data, Kaggle metadata, and MovieLens rating data (from Kaggle)

def extract_transform_load():
    # 2. Read in the kaggle metadata and MovieLens ratings CSV files as Pandas DataFrames.
    kaggle_metadata = pd.read_csv(f'{file_dir}/movies_metadata.csv', low_memory=False)
    ratings = pd.read_csv(f'{file_dir}/ratings.csv')
    
    # 3. Open the read the Wikipedia data JSON file.
    with open(f'{file_dir}/wikipedia-movies.json', mode='r') as file: wiki_movies_raw = json.load(file)
    
    # 4. Read in the raw wiki movie data as a Pandas DataFrame.
    wiki_movies_df = pd.DataFrame(wiki_movies_raw)
    
    # 5. Return the three DataFrames
    return wiki_movies_df, kaggle_metadata, ratings

# 6 Create the path to your file directory and variables for the three files. 
file_dir = 'Resources'
# Wikipedia data
wiki_file = f'{file_dir}/wikipedia.movies.json'
# Kaggle metadata
kaggle_file = f'{file_dir}/movies_metadata.csv'
# MovieLens rating data.
ratings_file = f'{file_dir}/ratings.csv'

# 7. Set the three variables in Step 6 equal to the function created in Step 1.
wiki_file, kaggle_file, ratings_file = extract_transform_load()

In [3]:
# 8. Set the DataFrames from the return statement equal to the file names in Step 6. 
wiki_movies_df = wiki_file
kaggle_metadata = kaggle_file
ratings = ratings_file

In [7]:
# 9. Check the wiki_movies_df DataFrame.
list(wiki_movies_df.head())

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resting place',
 'Occupation',
 'Years active',
 'Spouse(s)',
 'Children',
 'Parent(s)',
 'Genres',
 'Instruments',
 'Labels',
 'Website',
 'Traditional',
 'Mandarin',
 'Type',
 'Industry',
 'Fate',
 'Founded',
 'Founder',
 'Headquarters',
 'Parent',
 'Released',
 'Recorded',
 'Venue',
 'Length',
 'Label',
 'Director',
 'Producer',
 'Area',
 'Coordinates',
 'Status',
 'Opening date',
 'Closing date',
 'Replaced',
 'Replaced by',
 'Name',
 'Attraction type',
 'Music',
 'Duration',
 'Simplified Chinese',
 'Traditional Chinese',
 'Hanyu Pinyin',
 'Literal meaning',
 'Transcriptions',
 'Bopomofo',
 'Gwoyeu Romatzyh',
 'Wade–Giles',
 'IPA',
 'Yale Romanization',
 'Jyutping',
 'Hokkien POJ',
 'Animation by',
 'Color process',
 'Engine(s)',
 'Genre(s)',
 'Actor control',
 'Production company',
 'Release(s)',
 'Format(s)',
 'Simplified',
 'Characters',
 'Date premiered',
 'Place premiered',
 'Setting',
 'Original language',
 'Subject',
 'Published',
 'Dewey Decimal',
 'Text',
 'Illustrator',
 'Original title',
 'Published in English',
 'French',
 'Developed by',
 'Ending theme',
 'No. of seasons',
 'Nationality',
 'Portrayed by',
 'Alias',
 'Species',
 'Gender',
 'Family',
 'Alma mater',
 'Camera setup',
 'Novel(s)',
 'Comics',
 'Film(s)',
 'Screen story by',
 'Hangul',
 'Revised Romanization',
 'McCune–Reischauer',
 'Developer(s)',
 'Publisher(s)',
 'Designer(s)',
 'Programmer(s)',
 'Artist(s)',
 'Writer(s)',
 'Engine',
 'Platform(s)',
 'Release',
 'Mode(s)',
 'Original work',
 'Television series',
 'Japanese',
 'Hepburn',
 'Literally',
 'Cantonese',
 'Full name',
 'Height',
 'Seasons',
 'Chinese',
 'Other names',
 'Relatives',
 'Yiddish',
 'Formerly',
 'Key people',
 'Total assets',
 'Owner',
 'Number of employees',
 'Divisions',
 'Subsidiaries',
 'Arabic',
 'Romanized',
 'Predecessor',
 'Founders',
 'Area served',
 'Products',
 'Services',
 'Russian',
 'Hebrew',
 'Revenue',
 'Operating income',
 'Polish']

In [9]:
# 10. Check the kaggle_metadata DataFrame.
dict(kaggle_metadata)

{'adult': 0        False
 1        False
 2        False
 3        False
 4        False
          ...
 45461    False
 45462    False
 45463    False
 45464    False
 45465    False
 Name: adult, Length: 45466, dtype: object,
 'belongs_to_collection': 0        {'id': 10194, 'name': 'Toy Story Collection', ...
 1                                                      NaN
 2        {'id': 119050, 'name': 'Grumpy Old Men Collect...
 3                                                      NaN
 4        {'id': 96871, 'name': 'Father of the Bride Col...
                                ...
 45461                                                  NaN
 45462                                                  NaN
 45463                                                  NaN
 45464                                                  NaN
 45465                                                  NaN
 Name: belongs_to_collection, Length: 45466, dtype: object,
 'budget': 0        30000000
 1        65000000
 2               0
 3        16000000
 4               0
            ...
 45461           0
 45462           0
 45463           0
 45464           0
 45465           0
 Name: budget, Length: 45466, dtype: object,
 'genres': 0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
 1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
 2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
 3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
 4                           [{'id': 35, 'name': 'Comedy'}]
                                ...
 45461    [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
 45462                        [{'id': 18, 'name': 'Drama'}]
 45463    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
 45464                                                   []
 45465                                                   []
 Name: genres, Length: 45466, dtype: object,
 'homepage': 0        http://toystory.disney.com/toy-story
 1                                         NaN
 2                                         NaN
 3                                         NaN
 4                                         NaN
                          ...
 45461    http://www.imdb.com/title/tt6209470/
 45462                                     NaN
 45463                                     NaN
 45464                                     NaN
 45465                                     NaN
 Name: homepage, Length: 45466, dtype: object,
 'id': 0           862
 1          8844
 2         15602
 3         31357
 4         11862
           ...
 45461    439050
 45462    111109
 45463     67758
 45464    227506
 45465    461257
 Name: id, Length: 45466, dtype: object,
 'imdb_id': 0        tt0114709
 1        tt0113497
 2        tt0113228
 3        tt0114885
 4        tt0113041
            ...
 45461    tt6209470
 45462    tt2028550
 45463    tt0303758
 45464    tt0008536
 45465    tt6980792
 Name: imdb_id, Length: 45466, dtype: object,
 'original_language': 0        en
 1        en
 2        en
 3        en
 4        en
          ..
 45461    fa
 45462    tl
 45463    en
 45464    en
 45465    en
 Name: original_language, Length: 45466, dtype: object,
 'original_title': 0                          Toy Story
 1                            Jumanji
 2                   Grumpier Old Men
 3                  Waiting to Exhale
 4        Father of the Bride Part II
                     ...
 45461                        رگ خواب
 45462            Siglo ng Pagluluwal
 45463                       Betrayal
 45464            Satana likuyushchiy
 45465                       Queerama
 Name: original_title, Length: 45466, dtype: object,
 'overview': 0        Led by Woody, Andy's toys live happily in his ...
 1        When siblings Judy and Peter discover an encha...
 2        A family wedding reignites the ancient feud be...
 3        Cheated on, mistreated and stepped on, the wom...
 4        Just when George Banks has recovered from his ...
                                ...
 45461          Rising and falling between a man and woman.
 45462    An artist struggles to finish his work while a...
 45463    When one of her hits goes wrong, a professiona...
 45464    In a small town live two brothers, one a minis...
 45465    50 years after decriminalisation of homosexual...
 Name: overview, Length: 45466, dtype: object,
 'popularity': 0        21.946943
 1        17.015539
 2          11.7129
 3         3.859495
 4         8.387519
            ...
 45461     0.072051
 45462     0.178241
 45463     0.903007
 45464     0.003503
 45465     0.163015
 Name: popularity, Length: 45466, dtype: object,
 'poster_path': 0        /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
 1        /vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
 2        /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
 3        /16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
 4        /e64sOI48hQXyru7naBFyssKFxVd.jpg
                        ...
 45461    /jldsYflnId4tTWPx8es3uzsB1I8.jpg
 45462    /xZkmxsNmYXJbKVsTRLLx3pqGHx7.jpg
 45463    /d5bX92nDsISNhu3ZT69uHwmfCGw.jpg
 45464    /aorBPO7ak8e8iJKT5OcqYxU3jlK.jpg
 45465    /s5UkZt6NTsrS7ZF0Rh8nzupRlIU.jpg
 Name: poster_path, Length: 45466, dtype: object,
 'production_companies': 0           [{'name': 'Pixar Animation Studios', 'id': 3}]
 1        [{'name': 'TriStar Pictures', 'id': 559}, {'na...
 2        [{'name': 'Warner Bros.', 'id': 6194}, {'name'...
 3        [{'name': 'Twentieth Century Fox Film Corporat...
 4        [{'name': 'Sandollar Productions', 'id': 5842}...
                                ...
 45461                                                   []
 45462               [{'name': 'Sine Olivia', 'id': 19653}]
 45463    [{'name': 'American World Pictures', 'id': 6165}]
 45464                 [{'name': 'Yermoliev', 'id': 88753}]
 45465                                                   []
 Name: production_companies, Length: 45466, dtype: object,
 'production_countries': 0        [{'iso_3166_1': 'US', 'name': 'United States o...
 1        [{'iso_3166_1': 'US', 'name': 'United States o...
 2        [{'iso_3166_1': 'US', 'name': 'United States o...
 3        [{'iso_3166_1': 'US', 'name': 'United States o...
 4        [{'iso_3166_1': 'US', 'name': 'United States o...
                                ...
 45461               [{'iso_3166_1': 'IR', 'name': 'Iran'}]
 45462        [{'iso_3166_1': 'PH', 'name': 'Philippines'}]
 45463    [{'iso_3166_1': 'US', 'name': 'United States o...
 45464             [{'iso_3166_1': 'RU', 'name': 'Russia'}]
 45465     [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]
 Name: production_countries, Length: 45466, dtype: object,
 'release_date': 0        1995-10-30
 1        1995-12-15
 2        1995-12-22
 3        1995-12-22
 4        1995-02-10
             ...
 45461           NaN
 45462    2011-11-17
 45463    2003-08-01
 45464    1917-10-21
 45465    2017-06-09
 Name: release_date, Length: 45466, dtype: object,
 'revenue': 0        373554033.0
 1        262797249.0
 2                0.0
 3         81452156.0
 4         76578911.0
             ...
 45461            0.0
 45462            0.0
 45463            0.0
 45464            0.0
 45465            0.0
 Name: revenue, Length: 45466, dtype: float64,
 'runtime': 0         81.0
 1        104.0
 2        101.0
 3        127.0
 4        106.0
          ...
 45461     90.0
 45462    360.0
 45463     90.0
 45464     87.0
 45465     75.0
 Name: runtime, Length: 45466, dtype: float64,
 'spoken_languages': 0                 [{'iso_639_1': 'en', 'name': 'English'}]
 1        [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
 2                 [{'iso_639_1': 'en', 'name': 'English'}]
 3                 [{'iso_639_1': 'en', 'name': 'English'}]
 4                 [{'iso_639_1': 'en', 'name': 'English'}]
                                ...
 45461               [{'iso_639_1': 'fa', 'name': 'فارسی'}]
 45462                    [{'iso_639_1': 'tl', 'name': ''}]
 45463             [{'iso_639_1': 'en', 'name': 'English'}]
 45464                                                   []
 45465             [{'iso_639_1': 'en', 'name': 'English'}]
 Name: spoken_languages, Length: 45466, dtype: object,
 'status': 0        Released
 1        Released
 2        Released
 3        Released
 4        Released
            ...
 45461    Released
 45462    Released
 45463    Released
 45464    Released
 45465    Released
 Name: status, Length: 45466, dtype: object,
 'tagline': 0                                                      NaN
 1                Roll the dice and unleash the excitement!
 2        Still Yelling. Still Fighting. Still Ready for...
 3        Friends are the people who let you be yourself...
 4        Just When His World Is Back To Normal... He's ...
                                ...
 45461           Rising and falling between a man and woman
 45462                                                  NaN
 45463                               A deadly game of wits.
 45464                                                  NaN
 45465                                                  NaN
 Name: tagline, Length: 45466, dtype: object,
 'title': 0                          Toy Story
 1                            Jumanji
 2                   Grumpier Old Men
 3                  Waiting to Exhale
 4        Father of the Bride Part II
                     ...
 45461                         Subdue
 45462            Century of Birthing
 45463                       Betrayal
 45464               Satan Triumphant
 45465                       Queerama
 Name: title, Length: 45466, dtype: object,
 'video': 0        False
 1        False
 2        False
 3        False
 4        False
          ...
 45461    False
 45462    False
 45463    False
 45464    False
 45465    False
 Name: video, Length: 45466, dtype: object,
 'vote_average': 0        7.7
 1        6.9
 2        6.5
 3        6.1
 4        5.7
         ...
 45461    4.0
 45462    9.0
 45463    3.8
 45464    0.0
 45465    0.0
 Name: vote_average, Length: 45466, dtype: float64,
 'vote_count': 0        5415.0
 1        2413.0
 2          92.0
 3          34.0
 4         173.0
           ...
 45461       1.0
 45462       3.0
 45463       6.0
 45464       0.0
 45465       0.0
 Name: vote_count, Length: 45466, dtype: float64}

In [6]:
# 11. Check the ratings DataFrame.
ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556